// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRto2jy6P92eVB77vlKXzX98p-izhiCEM',
    appId: '1:452344006673:web:79f61f4e700f48637689b0',
    messagingSenderId: '452344006673',
    projectId: 'excel-learn-hub',
    authDomain: 'excel-learn-hub.firebaseapp.com',
    storageBucket: 'excel-learn-hub.firebasestorage.app',
    measurementId: 'G-35WS6DQ7NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvxXwOWKG27KmbkLZ_5NgL4ZriOI7pr_o',
    appId: '1:452344006673:android:a6d45a284098e44c7689b0',
    messagingSenderId: '452344006673',
    projectId: 'excel-learn-hub',
    storageBucket: 'excel-learn-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWrb72xA8fx_HNbS4ljIC4fRtnzLZgzt4',
    appId: '1:452344006673:ios:b0caa6dddfca62a27689b0',
    messagingSenderId: '452344006673',
    projectId: 'excel-learn-hub',
    storageBucket: 'excel-learn-hub.firebasestorage.app',
    iosBundleId: 'com.example.excelLearnHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWrb72xA8fx_HNbS4ljIC4fRtnzLZgzt4',
    appId: '1:452344006673:ios:b0caa6dddfca62a27689b0',
    messagingSenderId: '452344006673',
    projectId: 'excel-learn-hub',
    storageBucket: 'excel-learn-hub.firebasestorage.app',
    iosBundleId: 'com.example.excelLearnHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRto2jy6P92eVB77vlKXzX98p-izhiCEM',
    appId: '1:452344006673:web:602cdd5cb8a327897689b0',
    messagingSenderId: '452344006673',
    projectId: 'excel-learn-hub',
    authDomain: 'excel-learn-hub.firebaseapp.com',
    storageBucket: 'excel-learn-hub.firebasestorage.app',
    measurementId: 'G-Z2DBN2MFFZ',
  );
}
